package yajsdl.jna;
import com.sun.jna.Structure;
/**
 * <i>native declaration : /usr/include/SDL/SDL_sound.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class Sound_Version extends Structure {
	/// < major revision
	public int major;
	/// < minor revision
	public int minor;
	/// < patchlevel
	public int patch;
	public Sound_Version() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"major", "minor", "patch"});
	}
	/**
	 * @param major < major revision<br>
	 * @param minor < minor revision<br>
	 * @param patch < patchlevel
	 */
	public Sound_Version(int major, int minor, int patch) {
		super();
		this.major = major;
		this.minor = minor;
		this.patch = patch;
		initFieldOrder();
	}
	public static class ByReference extends Sound_Version implements Structure.ByReference {
		
	};
	public static class ByValue extends Sound_Version implements Structure.ByValue {
		
	};
}
