package org.yajsdl.jna;

import com.sun.jna.Structure;


/**
 * <i>native declaration : /usr/include/SDL/SDL_net.h</i><br>
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that
 * <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a
 * few opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a
 * href="http://rococoa.dev.java.net/">Rococoa</a>, or <a
 * href="http://jna.dev.java.net/">JNA</a>.
 */
public class _SDLNet_GenericSocket extends Structure {
    public int ready;


    public _SDLNet_GenericSocket() {
        super();
        initFieldOrder();
    }


    protected void initFieldOrder() {
        setFieldOrder( new java.lang.String[] { "ready" } );
    }


    public _SDLNet_GenericSocket(int ready) {
        super();
        this.ready = ready;
        initFieldOrder();
    }

    public static class ByReference extends _SDLNet_GenericSocket implements Structure.ByReference {

    };

    public static class ByValue extends _SDLNet_GenericSocket implements Structure.ByValue {

    };
}
