package org.yajsdl.jna;
import com.sun.jna.Structure;
/**
 * <i>native declaration : /usr/include/SDL/SDL_events.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SDL_JoyButtonEvent extends Structure {
	/**
	 * < SDL_JOYBUTTONDOWN or SDL_JOYBUTTONUP<br>
	 * C type : Uint8
	 */
	public byte type;
	/**
	 * < The joystick device index<br>
	 * C type : Uint8
	 */
	public byte which;
	/**
	 * < The joystick button index<br>
	 * C type : Uint8
	 */
	public byte button;
	/**
	 * < SDL_PRESSED or SDL_RELEASED<br>
	 * C type : Uint8
	 */
	public byte state;
	public SDL_JoyButtonEvent() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"type", "which", "button", "state"});
	}
	/**
	 * @param type < SDL_JOYBUTTONDOWN or SDL_JOYBUTTONUP<br>
	 * C type : Uint8<br>
	 * @param which < The joystick device index<br>
	 * C type : Uint8<br>
	 * @param button < The joystick button index<br>
	 * C type : Uint8<br>
	 * @param state < SDL_PRESSED or SDL_RELEASED<br>
	 * C type : Uint8
	 */
	public SDL_JoyButtonEvent(byte type, byte which, byte button, byte state) {
		super();
		this.type = type;
		this.which = which;
		this.button = button;
		this.state = state;
		initFieldOrder();
	}
	public static class ByReference extends SDL_JoyButtonEvent implements Structure.ByReference {
		
	};
	public static class ByValue extends SDL_JoyButtonEvent implements Structure.ByValue {
		
	};
}
