package org.yajsdl.jna;
import com.sun.jna.Structure;
/**
 * <i>native declaration : /usr/include/SDL/SDL_events.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SDL_JoyBallEvent extends Structure {
	/**
	 * < SDL_JOYBALLMOTION<br>
	 * C type : Uint8
	 */
	public byte type;
	/**
	 * < The joystick device index<br>
	 * C type : Uint8
	 */
	public byte which;
	/**
	 * < The joystick trackball index<br>
	 * C type : Uint8
	 */
	public byte ball;
	/**
	 * < The relative motion in the X direction<br>
	 * C type : Sint16
	 */
	public short xrel;
	/**
	 * < The relative motion in the Y direction<br>
	 * C type : Sint16
	 */
	public short yrel;
	public SDL_JoyBallEvent() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"type", "which", "ball", "xrel", "yrel"});
	}
	/**
	 * @param type < SDL_JOYBALLMOTION<br>
	 * C type : Uint8<br>
	 * @param which < The joystick device index<br>
	 * C type : Uint8<br>
	 * @param ball < The joystick trackball index<br>
	 * C type : Uint8<br>
	 * @param xrel < The relative motion in the X direction<br>
	 * C type : Sint16<br>
	 * @param yrel < The relative motion in the Y direction<br>
	 * C type : Sint16
	 */
	public SDL_JoyBallEvent(byte type, byte which, byte ball, short xrel, short yrel) {
		super();
		this.type = type;
		this.which = which;
		this.ball = ball;
		this.xrel = xrel;
		this.yrel = yrel;
		initFieldOrder();
	}
	public static class ByReference extends SDL_JoyBallEvent implements Structure.ByReference {
		
	};
	public static class ByValue extends SDL_JoyBallEvent implements Structure.ByValue {
		
	};
}
