package org.yajsdl.jna;
import com.sun.jna.Structure;
/**
 * <i>native declaration : /usr/include/SDL/SDL_version.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SDL_version extends Structure {
	/// C type : Uint8
	public byte major;
	/// C type : Uint8
	public byte minor;
	/// C type : Uint8
	public byte patch;
	public SDL_version() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"major", "minor", "patch"});
	}
	/**
	 * @param major C type : Uint8<br>
	 * @param minor C type : Uint8<br>
	 * @param patch C type : Uint8
	 */
	public SDL_version(byte major, byte minor, byte patch) {
		super();
		this.major = major;
		this.minor = minor;
		this.patch = patch;
		initFieldOrder();
	}
	public static class ByReference extends SDL_version implements Structure.ByReference {
		
	};
	public static class ByValue extends SDL_version implements Structure.ByValue {
		
	};
}
