package org.yajsdl.jna;

import com.sun.jna.Structure;


/**
 * <i>native declaration : /usr/include/SDL/SDL_events.h</i><br>
 * This file was autogenerated by <a
 * href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that
 * <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a
 * few opensource projects.</a>.<br>
 * For help, please visit <a
 * href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a
 * href="http://rococoa.dev.java.net/">Rococoa</a>, or <a
 * href="http://jna.dev.java.net/">JNA</a>.
 */
public class SDL_MouseMotionEvent extends Structure {
    /**
     * < SDL_MOUSEMOTION<br>
     * C type : Uint8
     */
    public byte  type;
    /**
     * < The mouse device index<br>
     * C type : Uint8
     */
    public byte  which;
    /**
     * < The current button state<br>
     * C type : Uint8
     */
    public byte  state;
    /**
     * < The X/Y coordinates of the mouse<br>
     * C type : Uint16
     */
    public short x;
    /**
     * < The X/Y coordinates of the mouse<br>
     * C type : Uint16
     */
    public short y;
    /**
     * < The relative motion in the X direction<br>
     * C type : Sint16
     */
    public short xrel;
    /**
     * < The relative motion in the Y direction<br>
     * C type : Sint16
     */
    public short yrel;


    public SDL_MouseMotionEvent() {
        super();
        initFieldOrder();
    }


    protected void initFieldOrder() {
        setFieldOrder( new java.lang.String[] { "type", "which", "state", "x", "y", "xrel", "yrel" } );
    }


    /**
     * @param type
     *            < SDL_MOUSEMOTION<br>
     *            C type : Uint8<br>
     * @param which
     *            < The mouse device index<br>
     *            C type : Uint8<br>
     * @param state
     *            < The current button state<br>
     *            C type : Uint8<br>
     * @param x
     *            < The X/Y coordinates of the mouse<br>
     *            C type : Uint16<br>
     * @param y
     *            < The X/Y coordinates of the mouse<br>
     *            C type : Uint16<br>
     * @param xrel
     *            < The relative motion in the X direction<br>
     *            C type : Sint16<br>
     * @param yrel
     *            < The relative motion in the Y direction<br>
     *            C type : Sint16
     */
    public SDL_MouseMotionEvent(byte type, byte which, byte state, short x, short y, short xrel, short yrel) {
        super();
        this.type = type;
        this.which = which;
        this.state = state;
        this.x = x;
        this.y = y;
        this.xrel = xrel;
        this.yrel = yrel;
        initFieldOrder();
    }

    public static class ByReference extends SDL_MouseMotionEvent implements Structure.ByReference {

    };

    public static class ByValue extends SDL_MouseMotionEvent implements Structure.ByValue {

    };
}
