package org.yajsdl.jna;
import com.sun.jna.Structure;
/**
 * <i>native declaration : /usr/include/SDL/SDL_video.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SDL_Palette extends Structure {
	public int ncolors;
	/// C type : SDL_Color*
	public org.yajsdl.jna.SDL_Color.ByReference colors;
	public SDL_Palette() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"ncolors", "colors"});
	}
	/// @param colors C type : SDL_Color*
	public SDL_Palette(int ncolors, org.yajsdl.jna.SDL_Color.ByReference colors) {
		super();
		this.ncolors = ncolors;
		this.colors = colors;
		initFieldOrder();
	}
	public static class ByReference extends SDL_Palette implements Structure.ByReference {
		
	};
	public static class ByValue extends SDL_Palette implements Structure.ByValue {
		
	};
}
