package org.yajsdl.jna;
import com.sun.jna.Structure;
/**
 * <i>native declaration : /usr/include/SDL/SDL_video.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SDL_Rect extends Structure {
	/// C type : Sint16
	public short x;
	/// C type : Sint16
	public short y;
	/// C type : Uint16
	public short w;
	/// C type : Uint16
	public short h;
	public SDL_Rect() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"x", "y", "w", "h"});
	}
	/**
	 * @param x C type : Sint16<br>
	 * @param y C type : Sint16<br>
	 * @param w C type : Uint16<br>
	 * @param h C type : Uint16
	 */
	public SDL_Rect(short x, short y, short w, short h) {
		super();
		this.x = x;
		this.y = y;
		this.w = w;
		this.h = h;
		initFieldOrder();
	}
	public static class ByReference extends SDL_Rect implements Structure.ByReference {
		
	};
	public static class ByValue extends SDL_Rect implements Structure.ByValue {
		
	};
}
