package org.yajsdl.jna;
import com.sun.jna.Structure;
/**
 * <i>native declaration : /usr/include/SDL/SDL_events.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SDL_ResizeEvent extends Structure {
	/**
	 * < SDL_VIDEORESIZE<br>
	 * C type : Uint8
	 */
	public byte type;
	/// < New width
	public int w;
	/// < New height
	public int h;
	public SDL_ResizeEvent() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"type", "w", "h"});
	}
	/**
	 * @param type < SDL_VIDEORESIZE<br>
	 * C type : Uint8<br>
	 * @param w < New width<br>
	 * @param h < New height
	 */
	public SDL_ResizeEvent(byte type, int w, int h) {
		super();
		this.type = type;
		this.w = w;
		this.h = h;
		initFieldOrder();
	}
	public static class ByReference extends SDL_ResizeEvent implements Structure.ByReference {
		
	};
	public static class ByValue extends SDL_ResizeEvent implements Structure.ByValue {
		
	};
}
