package org.yajsdl.jna;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.PointerByReference;
import com.sun.jna.ptr.ShortByReference;


/**
 * <i>native declaration : /usr/include/SDL/SDL_video.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SDL_Overlay extends Structure {
	/**
	 * < Read-only<br>
	 * C type : Uint32
	 */
	public int/* Uint32 */ format;
	/// < Read-only
	public int w;
	/// < Read-only
	public int h;
	/// < Read-only
	public int planes;
	/**
	 * < Read-only<br>
	 * C type : Uint16*
	 */
	public ShortByReference pitches;
	/**
	 * < Read-write<br>
	 * C type : Uint8**
	 */
	public PointerByReference pixels;
	/**
	 * @{<br>
	 * C type : private_yuvhwfuncs*
	 */
	public Pointer hwfuncs;
	/// C type : private_yuvhwdata*
	public Pointer hwdata;
	/// Conversion Error : hw_overlay:1 (This runtime does not support bit fields : JNA)
	/// Conversion Error : UnusedBits:31 (This runtime does not support bit fields : JNA)
	public SDL_Overlay() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"format", "w", "h", "planes", "pitches", "pixels", "hwfuncs", "hwdata"});
	}
	/**
	 * @param format < Read-only<br>
	 * C type : Uint32<br>
	 * @param w < Read-only<br>
	 * @param h < Read-only<br>
	 * @param planes < Read-only<br>
	 * @param pitches < Read-only<br>
	 * C type : Uint16*<br>
	 * @param pixels < Read-write<br>
	 * C type : Uint8**<br>
	 * @param hwfuncs @{<br>
	 * C type : private_yuvhwfuncs*<br>
	 * @param hwdata C type : private_yuvhwdata*
	 */
	public SDL_Overlay(int/* Uint32 */ format, int w, int h, int planes, ShortByReference pitches, PointerByReference pixels, Pointer hwfuncs, Pointer hwdata) {
		super();
		this.format = format;
		this.w = w;
		this.h = h;
		this.planes = planes;
		this.pitches = pitches;
		this.pixels = pixels;
		this.hwfuncs = hwfuncs;
		this.hwdata = hwdata;
		initFieldOrder();
	}
	public static class ByReference extends SDL_Overlay implements Structure.ByReference {
		
	};
	public static class ByValue extends SDL_Overlay implements Structure.ByValue {
		
	};
}
