package org.yajsdl.jna;
import com.sun.jna.Structure;
/**
 * <i>native declaration : /usr/include/SDL/SDL_events.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class SDL_QuitEvent extends Structure {
	/**
	 * < SDL_QUIT<br>
	 * C type : Uint8
	 */
	public byte type;
	public SDL_QuitEvent() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"type"});
	}
	/**
	 * @param type < SDL_QUIT<br>
	 * C type : Uint8
	 */
	public SDL_QuitEvent(byte type) {
		super();
		this.type = type;
		initFieldOrder();
	}
	public static class ByReference extends SDL_QuitEvent implements Structure.ByReference {
		
	};
	public static class ByValue extends SDL_QuitEvent implements Structure.ByValue {
		
	};
}
