package org.yajsdl.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * <i>native declaration : /usr/include/SDL/SDL_net.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class UDPpacket extends Structure {
	/// The src/dst channel of the packet
	public int channel;
	/**
	 * The packet data<br>
	 * C type : Uint8*
	 */
	public Pointer data;
	/// The length of the packet data
	public int len;
	/// The size of the data buffer
	public int maxlen;
	/// packet status after sending
	public int status;
	/**
	 * The source/dest address of an incoming/outgoing packet<br>
	 * C type : IPaddress
	 */
	public IPaddress address;
	public UDPpacket() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"channel", "data", "len", "maxlen", "status", "address"});
	}
	/**
	 * @param channel The src/dst channel of the packet<br>
	 * @param data The packet data<br>
	 * C type : Uint8*<br>
	 * @param len The length of the packet data<br>
	 * @param maxlen The size of the data buffer<br>
	 * @param status packet status after sending<br>
	 * @param address The source/dest address of an incoming/outgoing packet<br>
	 * C type : IPaddress
	 */
	public UDPpacket(int channel, Pointer data, int len, int maxlen, int status, IPaddress address) {
		super();
		this.channel = channel;
		this.data = data;
		this.len = len;
		this.maxlen = maxlen;
		this.status = status;
		this.address = address;
		initFieldOrder();
	}
	public static class ByReference extends UDPpacket implements Structure.ByReference {
		
	};
	public static class ByValue extends UDPpacket implements Structure.ByValue {
		
	};
}
